---
- name: "Insatlling LEMP Stack"
  hosts: ubuntu
  become: yes
  vars_files:
    - package_vars
    - secret_vars
    - nginx_vars
    - wordpress_vars
  tasks:

    - name: "Install Packges"
      apt:
        update_cache: true
        name: "{{ package }}"

    - name: "Restarting and Enabling Service"
      service:
        name: mariadb
        state: restarted
        enabled: true
            
    - name: "Setting Root Passsword"
      ignore_errors: true
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: "root"
        login_password: ""
        name: "root"
        password: "{{ mysql_root_password }}"
        host_all: true
            
    - name: "Removing Anonymous Users"
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: ""
        state: absent
        host_all: true
            
    - name: "Creating Database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_database }}"
        state: present
            
    - name: "Creating mysql user"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_user }}"
        host: "localhost"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_database }}.*:ALL"
    - name: "Configuring Vhost"
      template:
        src: ./site.conf.tmpl
        dest: /etc/nginx/sites-available/site.conf

    - name: "Enabling Conf file"
      file: 
        src: /etc/nginx/sites-available/site.conf
        dest: /etc/nginx/sites-enabled/site.conf
        state: link 
    
    - name: "Copying default conf File"
      copy:
        src: ./default
        dest: /etc/nginx/sites-available/default
    
    - name: "Restarting and Enabling Service"
      service:
        name: nginx
        state: restarted
        enabled: true
    
    - name: "Downloading Archive File {{ wp_url }}"
      get_url:
        url: "{{ wp_url }}"
        dest: /tmp/wordpress.tar.gz
            
    - name: "Extracting the File"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
            
    - name: "Copying Contents to the Doc-Root"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/{{ domain_name }}"
        remote_src: true
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
            
    - name: "Wordpress - Creating wp-config.php from template"
      template:
        src: ./wp-config.tmpl
        dest: "/var/www/{{ domain_name }}/wp-config.php"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"


   











